import type { Internship } from './types'

export const internships: Internship[] = [
  {
    id: 'product-design-google',
    role: 'Product Design Intern',
    company: 'Google',
    city: 'São Paulo, SP',
    modality: 'Híbrido',
    pay: 'R$ 2.400/mês',
    tags: ['Design', 'UX', 'Produto'],
    benefits: ['VR', 'Auxílio home office'],
    featured: false,
    logo: 'G',
    logoTone: 'blue',
  },
  {
    id: 'engenharia-nubank',
    role: 'Estágio em Engenharia de Software',
    company: 'Nubank',
    city: 'São Paulo, SP',
    modality: 'Remoto',
    pay: 'R$ 3.000/mês',
    tags: ['Engenharia de Software', 'Tecnologia', 'Desenvolvimento'],
    benefits: ['Candidatura rápida', 'VR'],
    featured: false,
    logo: 'Nu',
    logoTone: 'ink',
  },
  {
    id: 'dados-microsoft',
    role: 'Analista de Dados Júnior',
    company: 'Microsoft',
    city: 'São Paulo, SP',
    modality: 'Híbrido',
    pay: 'R$ 2.800/mês',
    tags: ['Dados', 'Tecnologia', 'Power BI'],
    benefits: ['VT + VR', 'Plano de saúde'],
    featured: true,
    logo: 'M',
    logoTone: 'blue',
  },
  {
    id: 'ux-mercado-livre',
    role: 'Estágio de UX Research',
    company: 'Mercado Livre',
    city: 'Todo o Brasil',
    modality: 'Remoto',
    pay: 'R$ 1.950/mês',
    tags: ['UX', 'Pesquisa', 'Design'],
    benefits: ['Wellhub', 'Horário flexível'],
    featured: true,
    logo: 'ML',
    logoTone: 'yellow',
  },
  {
    id: 'marketing-spotify',
    role: 'Marketing Digital',
    company: 'Spotify',
    city: 'Rio de Janeiro, RJ',
    modality: 'Presencial',
    pay: 'R$ 1.800/mês',
    tags: ['Marketing', 'Conteúdo', 'Social media'],
    benefits: ['Bolsa extra', 'Vale-cultura'],
    featured: true,
    logo: 'S',
    logoTone: 'green',
  },
  {
    id: 'administracao-vtex',
    role: 'Estágio em Administração',
    company: 'VTEX',
    city: 'Rio de Janeiro, RJ',
    modality: 'Híbrido',
    pay: 'R$ 2.100/mês',
    tags: ['Administração', 'Operações', 'Negócios'],
    benefits: ['VR', 'Inglês'],
    featured: true,
    logo: 'V',
    logoTone: 'red',
  },
]
